apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.name }}
  namespace: {{ include "teamcity.namespace" . }}
spec:
  replicas: {{ .Values.database.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.database.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.database.name }}
    spec:
      containers:
        - name: postgres
          image: {{ printf "%s:%s" .Values.database.image.repository .Values.database.image.tag }}
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.auth.secretName }}
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.auth.secretName }}
                  key: username
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.auth.secretName }}
                  key: database
            - name: PG_DATA
              value: /var/lib/postgresql/data
          ports:
            - containerPort: {{ .Values.database.service.port }}
          {{- if .Values.database.pvc.enabled }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          {{- end }}
      {{- if .Values.database.pvc.enabled }}
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Values.database.pvc.name }}
      {{- end }}
