apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: registry
spec:
  selector:
    app: registry-pod
  ports:
    - port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-pod
  template:
    metadata:
      labels:
        app: registry-pod
    spec:
      containers:
        - name: registry-container
          image: registry
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-pvc
              mountPath: /var/lib/registry
            - name: registry-auth
              mountPath: /auth
              readOnly: true
          resources:
            limits:
              cpu: "0.5"
              memory: "1Gi"
          env:
            - name: REGISTRY_HTTP_ADDR
              value: "0.0.0.0:5000"
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "registry-container"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: "/auth/registry.password"
      volumes:
        - name: registry-pvc
          persistentVolumeClaim:
            claimName: registry-pvc
        - name: registry-auth
          secret:
            secretName: registry-auth
