{{ if .Values.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teamcity.server.fullname" . }}-deployment
  namespace: {{ template "teamcity.namespace" . }}
  labels: {{ include "teamcity.server.label" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels: {{ include "teamcity.server.label" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "teamcity.server.label" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "teamcity.server.fullname" . }}
          image: {{ printf "%s:%s" .Values.server.image.repository (include "teamcity.server.imageTag" .) }}
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          {{- if .Values.server.pvc.enabled }}
          securityContext:
            runAsUser: {{ .Values.server.securityContext.runAsUser }}
          volumeMounts:
            - name:  server-data
              mountPath: /data/teamcity_server/datadir
          {{- end }}
          ports:
            - name: {{ template "teamcity.name" . }}-http
              containerPort: {{ .Values.server.service.port }}
              protocol: TCP
      {{- if .Values.server.pvc.enabled }}
      volumes:
        - name: server-data
          persistentVolumeClaim:
            claimName: {{ include "teamcity.server.fullname" . }}-pvc
      {{- end }}
{{ end }}