{{ if .Values.server.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "teamcity.server.fullname" . }}-ingress
  namespace: {{ template "teamcity.namespace" . }}
  labels: {{ include "teamcity.server.label" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.server.ingress.host }}
      http:
        paths: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "teamcity.server.fullname" . }}-svc
              port:
                number: 8111
  {{- if .Values.server.ingress.tls.enabled -}}
  tls:
    - hosts:
        - {{ .Values.server.ingress.host }}
      secretName: {{ .Values.server.ingress.tls.secretName }}
  {{- end -}}
{{ end }}